apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-dev
spec:
  project: project-dev
  source:
    repoURL: https://github.com/BAHALLA/gitops.git
    targetRevision: HEAD
    path: kustomize/environments/dev/infra/strimzi/
  destination:
    server: https://kubernetes.default.svc