all:
  hosts:
    master:
      ansible_host: 10.0.0.10
      ip: 10.0.0.10
      access_ip: 10.0.0.10
    node1:
      ansible_host: 10.0.0.11
      ip: 10.0.0.11
      access_ip: 110.0.0.11
    node2:
      ansible_host: 10.0.0.12
      ip: 10.0.0.12
      access_ip: 10.0.0.12
    console:
      ansible_host: 10.0.0.9
      ip: 10.0.0.9
      access_ip: 10.0.0.9
  children:
    nfs_node:
      hosts:
        console:
    kube_node:
      hosts:
        master:
        node1:
        node2:

