---
- name: Installer nfs utilities.
  tags: [server, client]
  package:
    name:
      - nfs-utils
      - libselinux-python
    state: present

- name: Ensure directories to export exist
  tags: [server]
  file:
    path: "{{ item.mount }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items: "{{ nfs_exports }}"

- name: Template exports file.
  tags: [server]
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs-server

- name: "Ensure service {{item}} enabled and started"
  tags: [server]
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap
