  
resources:
  - ../../base

patches:
  - target:
      kind: ClusterRoleBinding
    patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: kafka-dev
  - target:
      kind: RoleBinding
    patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: kafka-dev