---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress-dev