apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-promet-prometheus
spec:
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi